### ISSUE TITLE
Link csp.guru domain

### ISSUE THREAD

**Issue by richard-thonig** [repolicy/csp-guru#20]
After we uploaded the 2018-05 version of the dataset, we can link the domain.

**Comment by timtroendle** [comment]
@sjpfenninger Have you done this before and can support us here?

**Comment by sjpfenninger** [comment]
I'm actually not sure whether it's possible via GitHub to host a top-level domain from a repository, i.e. have `repolicy/csp-guru` appear directly on `https://csp.guru/`. I think it isn't. If you find that it's possible I can help you you set up the DNS entries. Otherwise, it is definitely possible to automate this (for free) via https://www.netlify.com/ which I'm also happy to lend a hand with.

**Comment by timtroendle** [comment]
I think it should be possible:
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

But I don't understand the necessary DNS configuration.

**Comment by timtroendle** [comment]
Done.

**Comment by sjpfenninger** [comment]
@richard-thonig you will probably need to update the branch name in Netlify then

**Comment by timtroendle** [comment]
I've done that already, thanks for the hint.
